# Generated by Django 4.1.2 on 2023-09-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhisWebsite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=255, unique=True)),
                ('url_length', models.IntegerField(choices=[(-1, 'Phish'), (0, 'Suspicious'), (1, 'NotPhish')], default=0)),
                ('having_at', models.IntegerField(choices=[(-1, 'Phish'), (0, 'Suspicious'), (1, 'NotPhish')], default=0)),
                ('double_slash_redirecting', models.IntegerField(choices=[(-1, 'Phish'), (0, 'Suspicious'), (1, 'NotPhish')], default=0)),
                ('HavingHyphen', models.IntegerField(choices=[(-1, 'Phish'), (0, 'Suspicious'), (1, 'NotPhish')], default=0)),
                ('age_of_domain', models.IntegerField(choices=[(-1, 'Phish'), (0, 'Suspicious'), (1, 'NotPhish')], default=0)),
                ('Favicon', models.IntegerField(choices=[(-1, 'Phish'), (0, 'Suspicious'), (1, 'NotPhish')], default=0)),
                ('Request_URL', models.IntegerField(choices=[(-1, 'Phish'), (0, 'Suspicious'), (1, 'NotPhish')], default=0)),
                ('Page_Rank', models.IntegerField(choices=[(-1, 'Phish'), (0, 'Suspicious'), (1, 'NotPhish')], default=0)),
                ('Google_Index', models.IntegerField(choices=[(-1, 'Phish'), (0, 'Suspicious'), (1, 'NotPhish')], default=0)),
            ],
        ),
    ]
